-- Script was generated by Devart dbForge Studio for MySQL, Version 3.60.347.0
-- Script date 3/12/2020 3:05:01 AM
-- Server version: 5.5.53
-- Client version: 4.1

/*!40014 SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0 */;

SET NAMES 'utf8';
USE realmd;

--
-- Definition for table account
--
CREATE TABLE account(
  id INT (11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Identifier',
  username VARCHAR (32) NOT NULL,
  sha_pass_hash VARCHAR (40) NOT NULL,
  gmlevel TINYINT (3) UNSIGNED NOT NULL DEFAULT 0,
  sessionkey LONGTEXT DEFAULT NULL,
  v LONGTEXT DEFAULT NULL,
  s LONGTEXT DEFAULT NULL,
  reg_mail VARCHAR (255) NOT NULL,
  token_key VARCHAR (100) NOT NULL,
  email TEXT DEFAULT NULL,
  joindate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_ip VARCHAR (30) NOT NULL DEFAULT '0.0.0.0',
  last_attempt_ip VARCHAR (15) NOT NULL DEFAULT '127.0.0.1',
  last_local_ip VARCHAR (30) NOT NULL DEFAULT '127.0.0.1',
  failed_logins INT (11) UNSIGNED NOT NULL DEFAULT 0,
  locked TINYINT (3) UNSIGNED NOT NULL DEFAULT 0,
  lock_country VARCHAR (2) NOT NULL DEFAULT '00',
  last_login TIMESTAMP DEFAULT '0000-00-00 00:00:00',
  last_pwd_reset TIMESTAMP DEFAULT '0000-00-00 00:00:00',
  online TINYINT (4) NOT NULL DEFAULT 0,
  expansion TINYINT (3) UNSIGNED NOT NULL DEFAULT 0,
  mutetime BIGINT (40) NOT NULL DEFAULT 0,
  mutereason VARCHAR (255) NOT NULL,
  muteby VARCHAR (50) NOT NULL,
  locale TINYINT (3) UNSIGNED NOT NULL DEFAULT 0,
  os VARCHAR (4) NOT NULL,
  recruiter INT (11) NOT NULL DEFAULT 0,
  current_realm TINYINT (3) UNSIGNED NOT NULL DEFAULT 0,
  banned TINYINT (1) UNSIGNED NOT NULL DEFAULT 0,
  mail_verif TINYINT (1) UNSIGNED NOT NULL DEFAULT 0,
  remember_token VARCHAR (100) NOT NULL,
  flags INT (10) UNSIGNED NOT NULL DEFAULT 0,
  security VARCHAR (255) DEFAULT NULL,
  pass_verif VARCHAR (255) DEFAULT NULL COMMENT 'Web recover password',
  email_verif TINYINT (1) NOT NULL DEFAULT 0 COMMENT 'Email verification',
  email_check VARCHAR (255) DEFAULT NULL,
  PRIMARY KEY (id),
  INDEX idx_gmlevel USING BTREE (gmlevel),
  UNIQUE INDEX idx_username USING BTREE (username)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = 'Account System';

--
-- Definition for table account_access
--
CREATE TABLE account_access(
  id INT (11) UNSIGNED NOT NULL,
  gmlevel TINYINT (3) UNSIGNED NOT NULL,
  RealmID INT (11) NOT NULL,
  PRIMARY KEY (id, RealmID)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table account_banned
--
CREATE TABLE account_banned(
  id BIGINT (20) NOT NULL DEFAULT 0 COMMENT 'Account id',
  bandate BIGINT (40) NOT NULL DEFAULT 0,
  unbandate BIGINT (40) NOT NULL DEFAULT 0,
  bannedby VARCHAR (50) NOT NULL,
  banreason VARCHAR (255) NOT NULL,
  active TINYINT (4) NOT NULL DEFAULT 1,
  realm TINYINT (4) NOT NULL DEFAULT 1,
  gmlevel TINYINT (4) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (id, bandate)
)
ENGINE = MYISAM
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = 'Ban List';

--
-- Definition for table antispam_blacklist
--
CREATE TABLE antispam_blacklist(
  word VARCHAR (32),
  PRIMARY KEY (word)
)
ENGINE = MYISAM
AVG_ROW_LENGTH = 20
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table antispam_detected
--
CREATE TABLE antispam_detected(
  id BIGINT (20) UNSIGNED NOT NULL DEFAULT 0,
  detectScore MEDIUMINT (5) NOT NULL DEFAULT 0,
  detectTime TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  reason VARCHAR (255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = MYISAM
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table antispam_replacement
--
CREATE TABLE antispam_replacement(
  `from` VARCHAR (32),
  `to` VARCHAR (32) NOT NULL,
  PRIMARY KEY (`from`)
)
ENGINE = MYISAM
AVG_ROW_LENGTH = 20
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table antispam_scores
--
CREATE TABLE antispam_scores(
  word VARCHAR (32),
  score TINYINT (3) UNSIGNED NOT NULL DEFAULT 0,
  type TINYINT (1) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (word)
)
ENGINE = MYISAM
AVG_ROW_LENGTH = 20
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table antispam_unicode
--
CREATE TABLE antispam_unicode(
  `from` MEDIUMINT (5) UNSIGNED NOT NULL DEFAULT 0,
  `to` MEDIUMINT (5) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`from`)
)
ENGINE = MYISAM
AVG_ROW_LENGTH = 7
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table cheat_detected
--
CREATE TABLE cheat_detected(
  id BIGINT (20) UNSIGNED NOT NULL AUTO_INCREMENT,
  detectScore MEDIUMINT (5) NOT NULL DEFAULT 0,
  detectTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  reason VARCHAR (255) DEFAULT NULL,
  minute INT (11) UNSIGNED NOT NULL DEFAULT 0,
  brainids VARCHAR (255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = MYISAM
AUTO_INCREMENT = 765
AVG_ROW_LENGTH = 92
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Definition for table ip_banned
--
CREATE TABLE ip_banned(
  ip VARCHAR (32) DEFAULT '0.0.0.0',
  bandate INT (11) NOT NULL,
  unbandate INT (11) NOT NULL,
  bannedby VARCHAR (50) NOT NULL DEFAULT '[Console]',
  banreason VARCHAR (50) NOT NULL DEFAULT 'no reason',
  PRIMARY KEY (ip)
)
ENGINE = MYISAM
CHARACTER SET utf8
COLLATE utf8_general_ci
COMMENT = 'Banned IPs';

--
-- Definition for table ip2nation
--
CREATE TABLE ip2nation(
  ip INT (11) UNSIGNED NOT NULL DEFAULT 0,
  country CHAR (2) NOT NULL,
  INDEX ip USING BTREE (ip)
)
ENGINE = INNODB
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table ip2nationcountries
--
CREATE TABLE ip2nationcountries(
  code VARCHAR (4),
  iso_code_2 VARCHAR (2) NOT NULL,
  iso_code_3 VARCHAR (3) DEFAULT NULL,
  iso_country VARCHAR (255) NOT NULL,
  country VARCHAR (255) NOT NULL,
  lat FLOAT NOT NULL DEFAULT 0,
  lon FLOAT NOT NULL DEFAULT 0,
  PRIMARY KEY (code),
  INDEX code USING BTREE (code)
)
ENGINE = INNODB
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

DELIMITER $$

--
-- Definition for procedure `!attribute3`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE `!attribute3`()
BEGIN
  UPDATE
    f_game.players
  SET
    passing = 3, speed = 3, ballcontrol = 3, shot = 3, defense = 3, heading = 3;

  UPDATE
    m_game.players
  SET
    passing = 5, speed = 3, ballcontrol = 5, shot = 5, defense = 5, heading = 3;

END
$$

--
-- Definition for procedure `!autoincrement`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE `!autoincrement`()
BEGIN

  ALTER TABLE realmd.account
    AUTO_INCREMENT = 1;

END
$$

--
-- Definition for procedure attribute3
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE attribute3()
BEGIN
  UPDATE
    f_game.players
  SET
    passing = 3, speed = 3, ballcontrol = 3, shot = 3, defense = 3, heading = 3;

  UPDATE
    m_game.players
  SET
    passing = 5, speed = 3, ballcontrol = 5, shot = 5, defense = 5, heading = 3;

END
$$

--
-- Definition for procedure autoincrement
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE autoincrement()
BEGIN
  DELETE
  FROM
    f_game.players;

  DELETE
  FROM
    f_game.teams;

  DELETE
  FROM
    f_game.market;
  DELETE
  FROM
    f_game.archive;


  DELETE
  FROM
    realmd.account;

  DELETE
  FROM
    realmd.cheat_detected;
  ALTER TABLE realmd.account
    AUTO_INCREMENT = 1;

  ALTER TABLE realmd.cheat_detected
    AUTO_INCREMENT = 1;

  ALTER TABLE f_game.players
    AUTO_INCREMENT = 1;
  ALTER TABLE f_game.teams
    AUTO_INCREMENT = 1;
  ALTER TABLE f_game.market
    AUTO_INCREMENT = 1;
  ALTER TABLE f_game.archive
    AUTO_INCREMENT = 1;

  OPTIMIZE TABLE realmd.account;
  OPTIMIZE TABLE f_game.players;
  OPTIMIZE TABLE f_game.teams;
  OPTIMIZE TABLE f_game.market;
  OPTIMIZE TABLE f_game.archive;




  DELETE
  FROM
    m_game.players;

  DELETE
  FROM
    m_game.teams;

  DELETE
  FROM
    m_game.market;
  DELETE
  FROM
    m_game.archive;


  DELETE
  FROM
    realmd.account;

  DELETE
  FROM
    realmd.cheat_detected;
  ALTER TABLE realmd.account
    AUTO_INCREMENT = 1;

  ALTER TABLE realmd.cheat_detected
    AUTO_INCREMENT = 1;

  ALTER TABLE m_game.players
    AUTO_INCREMENT = 1;
  ALTER TABLE m_game.teams
    AUTO_INCREMENT = 1;
  ALTER TABLE m_game.market
    AUTO_INCREMENT = 1;
  ALTER TABLE m_game.archive
    AUTO_INCREMENT = 1;

  OPTIMIZE TABLE realmd.account;
  OPTIMIZE TABLE m_game.players;
  OPTIMIZE TABLE m_game.teams;
  OPTIMIZE TABLE m_game.market;
  OPTIMIZE TABLE m_game.archive;



END
$$

--
-- Definition for procedure createdb
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE createdb()
BEGIN

  DROP TABLE IF EXISTS realmd.account;
  DROP TABLE IF EXISTS f_game.archive;
  DROP TABLE IF EXISTS f_game.market;
  DROP TABLE IF EXISTS f_game.players;
  DROP TABLE IF EXISTS f_game.teams;

  DROP TABLE IF EXISTS m_game.archive;
  DROP TABLE IF EXISTS m_game.market;
  DROP TABLE IF EXISTS m_game.players;
  DROP TABLE IF EXISTS m_game.teams;


  CREATE TABLE realmd.account(
    id INT (11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Identifier',
    username VARCHAR (32) NOT NULL,
    sha_pass_hash VARCHAR (40) NOT NULL,
    gmlevel TINYINT (3) UNSIGNED NOT NULL DEFAULT 0,
    sessionkey LONGTEXT DEFAULT NULL,
    v LONGTEXT DEFAULT NULL,
    s LONGTEXT DEFAULT NULL,
    reg_mail VARCHAR (255) NOT NULL,
    token_key VARCHAR (100) NOT NULL,
    email TEXT DEFAULT NULL,
    joindate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_ip VARCHAR (30) NOT NULL DEFAULT '0.0.0.0',
    last_attempt_ip VARCHAR (15) NOT NULL DEFAULT '127.0.0.1',
    last_local_ip VARCHAR (30) NOT NULL DEFAULT '127.0.0.1',
    failed_logins INT (11) UNSIGNED NOT NULL DEFAULT 0,
    locked TINYINT (3) UNSIGNED NOT NULL DEFAULT 0,
    lock_country VARCHAR (2) NOT NULL DEFAULT '00',
    last_login TIMESTAMP DEFAULT '0000-00-00 00:00:00',
    last_pwd_reset TIMESTAMP DEFAULT '0000-00-00 00:00:00',
    online TINYINT (4) NOT NULL DEFAULT 0,
    expansion TINYINT (3) UNSIGNED NOT NULL DEFAULT 0,
    mutetime BIGINT (40) NOT NULL DEFAULT 0,
    mutereason VARCHAR (255) NOT NULL,
    muteby VARCHAR (50) NOT NULL,
    locale TINYINT (3) UNSIGNED NOT NULL DEFAULT 0,
    os VARCHAR (4) NOT NULL,
    recruiter INT (11) NOT NULL DEFAULT 0,
    current_realm TINYINT (3) UNSIGNED NOT NULL DEFAULT 0,
    banned TINYINT (1) UNSIGNED NOT NULL DEFAULT 0,
    mail_verif TINYINT (1) UNSIGNED NOT NULL DEFAULT 0,
    remember_token VARCHAR (100) NOT NULL,
    flags INT (10) UNSIGNED NOT NULL DEFAULT 0,
    security VARCHAR (255) DEFAULT NULL,
    pass_verif VARCHAR (255) DEFAULT NULL COMMENT 'Web recover password',
    email_verif TINYINT (1) NOT NULL DEFAULT 0 COMMENT 'Email verification',
    email_check VARCHAR (255) DEFAULT NULL,
    PRIMARY KEY (id),
    INDEX idx_gmlevel USING BTREE (gmlevel),
    UNIQUE INDEX idx_username USING BTREE (username)
  )
  ENGINE = INNODB
  AUTO_INCREMENT = 1
  AVG_ROW_LENGTH = 540
  CHARACTER SET utf8
  COLLATE utf8_general_ci
  COMMENT = 'Account System';


  CREATE TABLE f_game.archive(
    guid INT (11) UNSIGNED NOT NULL AUTO_INCREMENT,
    season0 INT (11) UNSIGNED NOT NULL DEFAULT 0,
    seasonround0 TINYINT (4) NOT NULL DEFAULT 0,
    season1 INT (11) UNSIGNED NOT NULL DEFAULT 0,
    seasonround1 TINYINT (4) UNSIGNED NOT NULL DEFAULT 0,
    `year` INT (11) UNSIGNED NOT NULL DEFAULT 2018,
    month INT (11) UNSIGNED NOT NULL DEFAULT 1,
    day INT (11) UNSIGNED NOT NULL DEFAULT 1,
    hour INT (11) UNSIGNED NOT NULL DEFAULT 0,
    minute INT (11) UNSIGNED NOT NULL DEFAULT 1,
    second INT (11) UNSIGNED NOT NULL DEFAULT 1,
    guidteam0 INT (11) UNSIGNED DEFAULT NULL,
    guidteam1 INT (11) UNSIGNED DEFAULT NULL,
    gol0 INT (11) UNSIGNED NOT NULL DEFAULT 0,
    gol1 INT (11) UNSIGNED NOT NULL DEFAULT 0,
    matchinfo TEXT DEFAULT NULL,
    PRIMARY KEY (guid)
  )
  ENGINE = INNODB
  AUTO_INCREMENT = 1
  AVG_ROW_LENGTH = 744
  CHARACTER SET utf8
  COLLATE utf8_general_ci;

  CREATE TABLE f_game.market(
    guid INT (11) UNSIGNED NOT NULL AUTO_INCREMENT,
    guidplayer INT (11) UNSIGNED NOT NULL DEFAULT 0,
    name VARCHAR (25) DEFAULT NULL,
    sellprice INT (11) UNSIGNED NOT NULL DEFAULT 0,
    guidteam INT (11) UNSIGNED NOT NULL DEFAULT 0,
    speed TINYINT (4) NOT NULL DEFAULT 1,
    defense TINYINT (4) NOT NULL DEFAULT 1,
    passing TINYINT (4) NOT NULL DEFAULT 1,
    ballcontrol TINYINT (4) NOT NULL DEFAULT 1,
    shot TINYINT (4) UNSIGNED NOT NULL DEFAULT 1,
    heading TINYINT (4) UNSIGNED NOT NULL DEFAULT 1,
    talentid1 TINYINT (4) UNSIGNED NOT NULL DEFAULT 0,
    talentid2 TINYINT (4) UNSIGNED NOT NULL DEFAULT 0,
    history VARCHAR (20) NOT NULL DEFAULT '0,0,0,0,0,0',
    xp VARCHAR (255) NOT NULL DEFAULT '0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0',
    matches_played INT (11) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'div 38 ottiene l''età. 38 * 15 = totale partite.',
    matches_left INT (11) UNSIGNED NOT NULL DEFAULT 570,
    face INT (11) UNSIGNED NOT NULL DEFAULT 1,
    country INT (11) UNSIGNED NOT NULL DEFAULT 1,
    fitness TINYINT (4) UNSIGNED NOT NULL DEFAULT 1,
    morale TINYINT (4) UNSIGNED NOT NULL DEFAULT 1,
    PRIMARY KEY (guid)
  )
  ENGINE = INNODB
  AUTO_INCREMENT = 1
  AVG_ROW_LENGTH = 744
  CHARACTER SET utf8
  COLLATE utf8_general_ci;

  CREATE TABLE f_game.players(
    guid INT (11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'player global unique identifier',
    team INT (11) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'team attuale: game.teams.guid',
    name VARCHAR (25) DEFAULT NULL,
    matches_played INT (11) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'div 38 ottiene l''età. 38 * 15 = totale partite.',
    matches_left INT (11) UNSIGNED NOT NULL DEFAULT 570,
    formation_x TINYINT (4) NOT NULL DEFAULT 0,
    formation_y TINYINT (4) NOT NULL DEFAULT -1,
    talentid1 TINYINT (4) UNSIGNED NOT NULL DEFAULT 0,
    talentid2 TINYINT (4) UNSIGNED NOT NULL DEFAULT 0,
    speed TINYINT (4) UNSIGNED NOT NULL DEFAULT 1,
    defense TINYINT (4) UNSIGNED NOT NULL DEFAULT 1,
    passing TINYINT (4) UNSIGNED NOT NULL DEFAULT 1,
    ballcontrol TINYINT (4) UNSIGNED NOT NULL DEFAULT 1,
    heading TINYINT (4) UNSIGNED NOT NULL DEFAULT 1,
    shot TINYINT (4) UNSIGNED NOT NULL DEFAULT 1,
    stamina TINYINT (4) UNSIGNED NOT NULL DEFAULT 120,
    injured TINYINT (4) UNSIGNED NOT NULL DEFAULT 0,
    totyellowcard TINYINT (4) UNSIGNED NOT NULL DEFAULT 0,
    disqualified TINYINT (4) UNSIGNED NOT NULL DEFAULT 0,
    injured_penalty1 TINYINT (4) UNSIGNED NOT NULL DEFAULT 1 COMMENT '1,3,6 % lost attributes',
    injured_penalty2 TINYINT (4) UNSIGNED NOT NULL DEFAULT 1 COMMENT '2,4,8 % lost attributes',
    injured_penalty3 TINYINT (4) UNSIGNED NOT NULL DEFAULT 1 COMMENT '4,8,12 % lost attributes',
    deva1 TINYINT (4) UNSIGNED NOT NULL DEFAULT 1 COMMENT '5,15,30 % gain attributes every 100 ',
    deva2 TINYINT (4) UNSIGNED NOT NULL DEFAULT 1 COMMENT '5,10,20 % gain attributes every 300',
    deva3 TINYINT (4) UNSIGNED NOT NULL DEFAULT 1 COMMENT '1,5,10 % gain attributes every 300',
    devt1 TINYINT (4) UNSIGNED NOT NULL DEFAULT 1 COMMENT '4,8,12',
    devt2 TINYINT (4) UNSIGNED NOT NULL DEFAULT 1 COMMENT '2,4,8',
    devt3 TINYINT (4) UNSIGNED NOT NULL DEFAULT 1 COMMENT '1,3,6',
    history VARCHAR (20) NOT NULL DEFAULT '0,0,0,0,0,0',
    xp VARCHAR (255) NOT NULL DEFAULT '0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0' COMMENT 'NUM_TALENT  !!!!!!!',
    onmarket TINYINT (4) NOT NULL DEFAULT 0,
    face INT (11) NOT NULL DEFAULT 1,
    country INT (11) UNSIGNED NOT NULL DEFAULT 1,
    fitness TINYINT (4) UNSIGNED NOT NULL DEFAULT 1,
    morale TINYINT (4) UNSIGNED NOT NULL DEFAULT 1,
    PRIMARY KEY (guid)
  )
  ENGINE = INNODB
  AUTO_INCREMENT = 1
  AVG_ROW_LENGTH = 187
  CHARACTER SET utf8
  COLLATE utf8_general_ci;

  CREATE TABLE f_game.teams(
    guid INT (11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Global Unique Identifier',
    account INT (11) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Account Identifier',
    worldteam INT (10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'id che punta a world.team .  quindi a world.country ',
    country INT (11) UNSIGNED NOT NULL DEFAULT 0,
    teamname VARCHAR (35) NOT NULL,
    nextha TINYINT (4) NOT NULL DEFAULT 0,
    money INT (10) UNSIGNED NOT NULL DEFAULT 500,
    uniformh VARCHAR (20) DEFAULT '0,0,0,0',
    uniforma VARCHAR (20) DEFAULT '1,1,1,1',
    bot TINYINT (4) NOT NULL DEFAULT 0,
    mi INT (11) NOT NULL DEFAULT 0,
    points INT (11) UNSIGNED NOT NULL DEFAULT 0,
    matchesplayed INT (11) NOT NULL DEFAULT 0,
    season INT (11) NOT NULL DEFAULT 1,
    rank INT (11) UNSIGNED NOT NULL DEFAULT 5,
    youngqueue INT (11) UNSIGNED NOT NULL DEFAULT 0,
    online TINYINT (3) UNSIGNED NOT NULL DEFAULT 0,
    totaltime INT (11) UNSIGNED NOT NULL DEFAULT 0,
    leveltime INT (11) UNSIGNED NOT NULL DEFAULT 0,
    logout_time BIGINT (20) UNSIGNED NOT NULL DEFAULT 0,
    at_login INT (11) UNSIGNED NOT NULL DEFAULT 0,
    zone INT (11) UNSIGNED NOT NULL DEFAULT 0,
    death_expire_time BIGINT (20) UNSIGNED NOT NULL DEFAULT 0,
    deleteDate BIGINT (20) DEFAULT NULL,
    PRIMARY KEY (guid),
    INDEX idx_account USING BTREE (account),
    INDEX idx_online USING BTREE (online)
  )
  ENGINE = INNODB
  AUTO_INCREMENT = 1
  AVG_ROW_LENGTH = 163
  CHARACTER SET utf8
  COLLATE utf8_general_ci
  COMMENT = 'Player System';




  CREATE TABLE m_game.archive(
    guid INT (11) UNSIGNED NOT NULL AUTO_INCREMENT,
    season0 INT (11) UNSIGNED NOT NULL DEFAULT 0,
    seasonround0 TINYINT (4) NOT NULL DEFAULT 0,
    season1 INT (11) UNSIGNED NOT NULL DEFAULT 0,
    seasonround1 TINYINT (4) UNSIGNED NOT NULL DEFAULT 0,
    `year` INT (11) UNSIGNED NOT NULL DEFAULT 2018,
    month INT (11) UNSIGNED NOT NULL DEFAULT 1,
    day INT (11) UNSIGNED NOT NULL DEFAULT 1,
    hour INT (11) UNSIGNED NOT NULL DEFAULT 0,
    minute INT (11) UNSIGNED NOT NULL DEFAULT 1,
    second INT (11) UNSIGNED NOT NULL DEFAULT 1,
    guidteam0 INT (11) UNSIGNED DEFAULT NULL,
    guidteam1 INT (11) UNSIGNED DEFAULT NULL,
    gol0 INT (11) UNSIGNED NOT NULL DEFAULT 0,
    gol1 INT (11) UNSIGNED NOT NULL DEFAULT 0,
    matchinfo TEXT DEFAULT NULL,
    PRIMARY KEY (guid)
  )
  ENGINE = INNODB
  AUTO_INCREMENT = 1
  AVG_ROW_LENGTH = 744
  CHARACTER SET utf8
  COLLATE utf8_general_ci;

  CREATE TABLE m_game.market(
    guid INT (11) UNSIGNED NOT NULL AUTO_INCREMENT,
    guidplayer INT (11) UNSIGNED NOT NULL DEFAULT 0,
    name VARCHAR (25) DEFAULT NULL,
    sellprice INT (11) UNSIGNED NOT NULL DEFAULT 0,
    guidteam INT (11) UNSIGNED NOT NULL DEFAULT 0,
    speed TINYINT (4) NOT NULL DEFAULT 1,
    defense TINYINT (4) NOT NULL DEFAULT 1,
    passing TINYINT (4) NOT NULL DEFAULT 1,
    ballcontrol TINYINT (4) NOT NULL DEFAULT 1,
    shot TINYINT (4) UNSIGNED NOT NULL DEFAULT 1,
    heading TINYINT (4) UNSIGNED NOT NULL DEFAULT 1,
    talentid1 TINYINT (4) UNSIGNED NOT NULL DEFAULT 0,
    talentid2 TINYINT (4) UNSIGNED NOT NULL DEFAULT 0,
    history VARCHAR (20) NOT NULL DEFAULT '0,0,0,0,0,0',
    xp VARCHAR (255) NOT NULL DEFAULT '0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0',
    matches_played INT (11) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'div 38 ottiene l''età. 38 * 15 = totale partite.',
    matches_left INT (11) UNSIGNED NOT NULL DEFAULT 570,
    face INT (11) UNSIGNED NOT NULL DEFAULT 1,
    country INT (11) UNSIGNED NOT NULL DEFAULT 1,
    fitness TINYINT (4) UNSIGNED NOT NULL DEFAULT 1,
    morale TINYINT (4) UNSIGNED NOT NULL DEFAULT 1,
    PRIMARY KEY (guid)
  )
  ENGINE = INNODB
  AUTO_INCREMENT = 1
  AVG_ROW_LENGTH = 744
  CHARACTER SET utf8
  COLLATE utf8_general_ci;

  CREATE TABLE m_game.players(
    guid INT (11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'player global unique identifier',
    team INT (11) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'team attuale: game.teams.guid',
    name VARCHAR (25) DEFAULT NULL,
    matches_played INT (11) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'div 38 ottiene l''età. 38 * 15 = totale partite.',
    matches_left INT (11) UNSIGNED NOT NULL DEFAULT 570,
    formation_x TINYINT (4) NOT NULL DEFAULT 0,
    formation_y TINYINT (4) NOT NULL DEFAULT -1,
    talentid1 TINYINT (4) UNSIGNED NOT NULL DEFAULT 0,
    talentid2 TINYINT (4) UNSIGNED NOT NULL DEFAULT 0,
    speed TINYINT (4) UNSIGNED NOT NULL DEFAULT 1,
    defense TINYINT (4) UNSIGNED NOT NULL DEFAULT 1,
    passing TINYINT (4) UNSIGNED NOT NULL DEFAULT 1,
    ballcontrol TINYINT (4) UNSIGNED NOT NULL DEFAULT 1,
    heading TINYINT (4) UNSIGNED NOT NULL DEFAULT 1,
    shot TINYINT (4) UNSIGNED NOT NULL DEFAULT 1,
    stamina TINYINT (4) UNSIGNED NOT NULL DEFAULT 120,
    injured TINYINT (4) UNSIGNED NOT NULL DEFAULT 0,
    totyellowcard TINYINT (4) UNSIGNED NOT NULL DEFAULT 0,
    disqualified TINYINT (4) UNSIGNED NOT NULL DEFAULT 0,
    injured_penalty1 TINYINT (4) UNSIGNED NOT NULL DEFAULT 1 COMMENT '1,3,6 % lost attributes',
    injured_penalty2 TINYINT (4) UNSIGNED NOT NULL DEFAULT 1 COMMENT '2,4,8 % lost attributes',
    injured_penalty3 TINYINT (4) UNSIGNED NOT NULL DEFAULT 1 COMMENT '4,8,12 % lost attributes',
    deva1 TINYINT (4) UNSIGNED NOT NULL DEFAULT 1 COMMENT '5,15,30 % gain attributes every 100 ',
    deva2 TINYINT (4) UNSIGNED NOT NULL DEFAULT 1 COMMENT '5,10,20 % gain attributes every 300',
    deva3 TINYINT (4) UNSIGNED NOT NULL DEFAULT 1 COMMENT '1,5,10 % gain attributes every 300',
    devt1 TINYINT (4) UNSIGNED NOT NULL DEFAULT 1 COMMENT '4,8,12',
    devt2 TINYINT (4) UNSIGNED NOT NULL DEFAULT 1 COMMENT '2,4,8',
    devt3 TINYINT (4) UNSIGNED NOT NULL DEFAULT 1 COMMENT '1,3,6',
    history VARCHAR (20) NOT NULL DEFAULT '0,0,0,0,0,0',
    xp VARCHAR (255) NOT NULL DEFAULT '0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0' COMMENT 'NUM_TALENT  !!!!!!!',
    onmarket TINYINT (4) NOT NULL DEFAULT 0,
    face INT (11) NOT NULL DEFAULT 1,
    country INT (11) UNSIGNED NOT NULL DEFAULT 1,
    fitness TINYINT (4) UNSIGNED NOT NULL DEFAULT 1,
    morale TINYINT (4) UNSIGNED NOT NULL DEFAULT 1,
    PRIMARY KEY (guid)
  )
  ENGINE = INNODB
  AUTO_INCREMENT = 1
  AVG_ROW_LENGTH = 187
  CHARACTER SET utf8
  COLLATE utf8_general_ci;

  CREATE TABLE m_game.teams(
    guid INT (11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Global Unique Identifier',
    account INT (11) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Account Identifier',
    worldteam INT (10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'id che punta a world.team .  quindi a world.country ',
    country INT (11) UNSIGNED NOT NULL DEFAULT 0,
    teamname VARCHAR (35) NOT NULL,
    nextha TINYINT (4) NOT NULL DEFAULT 0,
    money INT (10) UNSIGNED NOT NULL DEFAULT 500,
    uniformh VARCHAR (20) DEFAULT '0,0,0,0',
    uniforma VARCHAR (20) DEFAULT '1,1,1,1',
    bot TINYINT (4) NOT NULL DEFAULT 0,
    mi INT (11) NOT NULL DEFAULT 0,
    points INT (11) UNSIGNED NOT NULL DEFAULT 0,
    matchesplayed INT (11) NOT NULL DEFAULT 0,
    season INT (11) NOT NULL DEFAULT 1,
    rank INT (11) UNSIGNED NOT NULL DEFAULT 5,
    youngqueue INT (11) UNSIGNED NOT NULL DEFAULT 0,
    online TINYINT (3) UNSIGNED NOT NULL DEFAULT 0,
    totaltime INT (11) UNSIGNED NOT NULL DEFAULT 0,
    leveltime INT (11) UNSIGNED NOT NULL DEFAULT 0,
    logout_time BIGINT (20) UNSIGNED NOT NULL DEFAULT 0,
    at_login INT (11) UNSIGNED NOT NULL DEFAULT 0,
    zone INT (11) UNSIGNED NOT NULL DEFAULT 0,
    death_expire_time BIGINT (20) UNSIGNED NOT NULL DEFAULT 0,
    deleteDate BIGINT (20) DEFAULT NULL,
    PRIMARY KEY (guid),
    INDEX idx_account USING BTREE (account),
    INDEX idx_online USING BTREE (online)
  )
  ENGINE = INNODB
  AUTO_INCREMENT = 1
  AVG_ROW_LENGTH = 163
  CHARACTER SET utf8
  COLLATE utf8_general_ci
  COMMENT = 'Player System';

END
$$

--
-- Definition for procedure procedure2
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE procedure2()
BEGIN

END
$$

DELIMITER ;

-- 
-- Dumping data for table account
-- 
-- Table does not contain any data (it is empty)

-- 
-- Dumping data for table account_access
-- 
INSERT INTO account_access VALUES (1, 6, 1);

-- 
-- Dumping data for table account_banned
-- 
-- Table does not contain any data (it is empty)

-- 
-- Dumping data for table antispam_blacklist
-- 
INSERT INTO antispam_blacklist VALUES ('4GAMEPOWER');
INSERT INTO antispam_blacklist VALUES ('ELYSIUMAEWOW');
INSERT INTO antispam_blacklist VALUES ('ELYSIUMKYWOW');
INSERT INTO antispam_blacklist VALUES ('ELYSIUMORWOW');
INSERT INTO antispam_blacklist VALUES ('ELYSIUMRDWOW');
INSERT INTO antispam_blacklist VALUES ('ELYSIUMRSWOW');
INSERT INTO antispam_blacklist VALUES ('G4W@W');
INSERT INTO antispam_blacklist VALUES ('G4WOW');
INSERT INTO antispam_blacklist VALUES ('GOLD4MMO');
INSERT INTO antispam_blacklist VALUES ('GOLDCEO');
INSERT INTO antispam_blacklist VALUES ('GOLDDEAL');
INSERT INTO antispam_blacklist VALUES ('GOLDINSIDER');
INSERT INTO antispam_blacklist VALUES ('ILOVEUGOLD');
INSERT INTO antispam_blacklist VALUES ('ITEM4GAME');
INSERT INTO antispam_blacklist VALUES ('ITEM4WOW');
INSERT INTO antispam_blacklist VALUES ('MMOGO');
INSERT INTO antispam_blacklist VALUES ('MMOLORD');
INSERT INTO antispam_blacklist VALUES ('MMOOK');
INSERT INTO antispam_blacklist VALUES ('MMOSE');
INSERT INTO antispam_blacklist VALUES ('MMOTANK');
INSERT INTO antispam_blacklist VALUES ('MONEYFORGAMES');
INSERT INTO antispam_blacklist VALUES ('NOST100');
INSERT INTO antispam_blacklist VALUES ('NOST1OO');
INSERT INTO antispam_blacklist VALUES ('OKOGAME');
INSERT INTO antispam_blacklist VALUES ('OKOGAMES');
INSERT INTO antispam_blacklist VALUES ('OKOGOMES');
INSERT INTO antispam_blacklist VALUES ('PVPBANK');
INSERT INTO antispam_blacklist VALUES ('RNRNOOK');
INSERT INTO antispam_blacklist VALUES ('RNRNOSE');
INSERT INTO antispam_blacklist VALUES ('SELLNGOLD');
INSERT INTO antispam_blacklist VALUES ('SINBAGAME');
INSERT INTO antispam_blacklist VALUES ('SINBAGOLD');
INSERT INTO antispam_blacklist VALUES ('SINBAONLINE');
INSERT INTO antispam_blacklist VALUES ('SUSANGAME');
INSERT INTO antispam_blacklist VALUES ('WOWMARY');
INSERT INTO antispam_blacklist VALUES ('WTSITEM');
INSERT INTO antispam_blacklist VALUES ('X2GOLD');
INSERT INTO antispam_blacklist VALUES ('XIAOBAIMOSHOUJINGJI');

-- 
-- Dumping data for table antispam_detected
-- 
-- Table does not contain any data (it is empty)

-- 
-- Dumping data for table antispam_replacement
-- 
INSERT INTO antispam_replacement VALUES ('\\\\/\\\\/', 'W');
INSERT INTO antispam_replacement VALUES ('/\\/\\', 'M');
INSERT INTO antispam_replacement VALUES ('0', 'O');
INSERT INTO antispam_replacement VALUES ('...hic!', '');
INSERT INTO antispam_replacement VALUES ('()', 'O');
INSERT INTO antispam_replacement VALUES ('\\/\\/', 'W');
INSERT INTO antispam_replacement VALUES ('/\\\\', 'A');
INSERT INTO antispam_replacement VALUES ('VV', 'W');
INSERT INTO antispam_replacement VALUES ('@', 'O');
INSERT INTO antispam_replacement VALUES ('/V\\', 'M');
INSERT INTO antispam_replacement VALUES ('/\\\\/\\\\', 'M');
INSERT INTO antispam_replacement VALUES ('㎜', 'MM');
INSERT INTO antispam_replacement VALUES ('!<', 'K');

-- 
-- Dumping data for table antispam_scores
-- 
INSERT INTO antispam_scores VALUES ('>>', 1, 1);
INSERT INTO antispam_scores VALUES ('<<', 1, 1);
INSERT INTO antispam_scores VALUES ('5OG', 1, 1);
INSERT INTO antispam_scores VALUES ('$', 2, 1);
INSERT INTO antispam_scores VALUES ('MOTANK', 4, 0);
INSERT INTO antispam_scores VALUES ('\\\\', 2, 1);
INSERT INTO antispam_scores VALUES ('ACOUNT', 1, 0);
INSERT INTO antispam_scores VALUES ('CHEAP', 2, 0);
INSERT INTO antispam_scores VALUES ('LEVELING', 1, 0);
INSERT INTO antispam_scores VALUES ('LEVLING', 1, 0);
INSERT INTO antispam_scores VALUES ('LEVILING', 1, 0);
INSERT INTO antispam_scores VALUES ('LVLING', 1, 0);
INSERT INTO antispam_scores VALUES ('SAFE', 1, 0);
INSERT INTO antispam_scores VALUES ('SERVICE', 1, 0);
INSERT INTO antispam_scores VALUES ('NOST', 1, 0);
INSERT INTO antispam_scores VALUES ('COM', 1, 0);
INSERT INTO antispam_scores VALUES ('PRICE', 2, 0);
INSERT INTO antispam_scores VALUES ('GOLD', 2, 0);
INSERT INTO antispam_scores VALUES ('SKYPE', 2, 0);
INSERT INTO antispam_scores VALUES ('EPIC', 2, 0);
INSERT INTO antispam_scores VALUES ('DOLARS', 2, 0);
INSERT INTO antispam_scores VALUES ('PROFESIONAL', 2, 0);
INSERT INTO antispam_scores VALUES ('RELIABLE', 2, 0);
INSERT INTO antispam_scores VALUES ('PROMOTION', 2, 0);
INSERT INTO antispam_scores VALUES ('DELIVER', 2, 0);
INSERT INTO antispam_scores VALUES ('NAX', 2, 0);
INSERT INTO antispam_scores VALUES ('GAMES', 2, 0);
INSERT INTO antispam_scores VALUES ('GRETINGS', 2, 0);
INSERT INTO antispam_scores VALUES ('WEBSITE', 2, 0);
INSERT INTO antispam_scores VALUES ('GOID', 2, 0);
INSERT INTO antispam_scores VALUES ('ITEM4', 5, 1);
INSERT INTO antispam_scores VALUES ('1OO', 2, 1);
INSERT INTO antispam_scores VALUES ('POWER', 1, 0);
INSERT INTO antispam_scores VALUES ('SELGOLD', 2, 0);
INSERT INTO antispam_scores VALUES ('FAST', 1, 0);
INSERT INTO antispam_scores VALUES ('25G', 2, 1);
INSERT INTO antispam_scores VALUES ('981526249', 3, 1);
INSERT INTO antispam_scores VALUES ('XIAOYUAN9921521', 3, 1);
INSERT INTO antispam_scores VALUES ('MANFARM', 1, 1);
INSERT INTO antispam_scores VALUES ('USD', 2, 0);
INSERT INTO antispam_scores VALUES ('GWOW', 3, 0);
INSERT INTO antispam_scores VALUES ('EUR', 2, 0);
INSERT INTO antispam_scores VALUES ('80G', 1, 1);
INSERT INTO antispam_scores VALUES ('OKO', 1, 0);
INSERT INTO antispam_scores VALUES ('G4', 2, 1);
INSERT INTO antispam_scores VALUES ('2OG', 1, 1);
INSERT INTO antispam_scores VALUES ('MSD', 3, 0);
INSERT INTO antispam_scores VALUES ('3VV', 3, 1);
INSERT INTO antispam_scores VALUES ('3W', 2, 1);
INSERT INTO antispam_scores VALUES ('SELL', 1, 1);
INSERT INTO antispam_scores VALUES ('WVWOKO', 4, 0);
INSERT INTO antispam_scores VALUES ('G=$', 3, 1);
INSERT INTO antispam_scores VALUES ('1OG', 1, 0);
INSERT INTO antispam_scores VALUES ('COIN', 0, 1);
INSERT INTO antispam_scores VALUES ('P0VVER', 2, 1);
INSERT INTO antispam_scores VALUES ('IEVEIING', 2, 1);
INSERT INTO antispam_scores VALUES ('GO1D', 2, 1);
INSERT INTO antispam_scores VALUES ('POWERLEVELING', 2, 0);

-- 
-- Dumping data for table antispam_unicode
-- 
INSERT INTO antispam_unicode VALUES (1063, 52);
INSERT INTO antispam_unicode VALUES (1054, 79);
INSERT INTO antispam_unicode VALUES (1057, 67);
INSERT INTO antispam_unicode VALUES (1052, 77);
INSERT INTO antispam_unicode VALUES (927, 79);
INSERT INTO antispam_unicode VALUES (1050, 75);
INSERT INTO antispam_unicode VALUES (913, 65);
INSERT INTO antispam_unicode VALUES (917, 69);
INSERT INTO antispam_unicode VALUES (1062, 85);
INSERT INTO antispam_unicode VALUES (9675, 79);
INSERT INTO antispam_unicode VALUES (1040, 65);
INSERT INTO antispam_unicode VALUES (1058, 84);
INSERT INTO antispam_unicode VALUES (1064, 87);
INSERT INTO antispam_unicode VALUES (1025, 69);
INSERT INTO antispam_unicode VALUES (1055, 78);
INSERT INTO antispam_unicode VALUES (1065, 87);
INSERT INTO antispam_unicode VALUES (922, 75);
INSERT INTO antispam_unicode VALUES (924, 77);
INSERT INTO antispam_unicode VALUES (1045, 69);
INSERT INTO antispam_unicode VALUES (968, 87);
INSERT INTO antispam_unicode VALUES (192, 65);
INSERT INTO antispam_unicode VALUES (210, 79);
INSERT INTO antispam_unicode VALUES (211, 79);
INSERT INTO antispam_unicode VALUES (242, 79);
INSERT INTO antispam_unicode VALUES (324, 78);
INSERT INTO antispam_unicode VALUES (328, 78);
INSERT INTO antispam_unicode VALUES (332, 79);
INSERT INTO antispam_unicode VALUES (466, 79);
INSERT INTO antispam_unicode VALUES (59336, 78);
INSERT INTO antispam_unicode VALUES (12562, 84);
INSERT INTO antispam_unicode VALUES (8745, 78);
INSERT INTO antispam_unicode VALUES (65325, 77);
INSERT INTO antispam_unicode VALUES (959, 79);
INSERT INTO antispam_unicode VALUES (945, 65);
INSERT INTO antispam_unicode VALUES (954, 75);
INSERT INTO antispam_unicode VALUES (12295, 79);
INSERT INTO antispam_unicode VALUES (65323, 75);
INSERT INTO antispam_unicode VALUES (65296, 79);
INSERT INTO antispam_unicode VALUES (65355, 75);
INSERT INTO antispam_unicode VALUES (65357, 77);
INSERT INTO antispam_unicode VALUES (65319, 71);
INSERT INTO antispam_unicode VALUES (925, 78);

-- 
-- Dumping data for table cheat_detected
-- 
INSERT INTO cheat_detected VALUES (764, 0, '2020-03-11 01:23:02', ' checkformation InQueue,InliveMatch,inSpectator: : queue', 0, NULL);

-- 
-- Dumping data for table ip_banned
-- 
-- Table does not contain any data (it is empty)

-- 
-- Dumping data for table ip2nation
-- 
-- Table does not contain any data (it is empty)

-- 
-- Dumping data for table ip2nationcountries
-- 
-- Table does not contain any data (it is empty)

/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;

